add_newline = false 
command_timeout = 0
scan_timeout = 0
format = "$username$directory"

[username]
format = "[$user]($style_user)@"
style_user = "bold #FFB86C" # soft orange
disabled = true

[directory]
style = "bold #79D4FF" # cyan-ish
read_only = "ğŸ”’"
read_only_style = "bold #FF6B6B"
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "â€¦/"
format = "[$path]($style)"

[character]
success_symbol = "[â¯](bold #A6E22E)"
error_symbol = "[âœ–](bold #FF6B6B)"
vimcmd_symbol = "[â®](bold #A6E22E)"

[time]
format = "on [$time]($style)"
style = "#6272A4"

[cmd_duration]
min_time = 2000
format = "took [$duration]($style)"
style = "bold #6272A4"
